name: 'Build and test'

on:
  push:
    branches:
      - main
  
jobs:
  BuildAndTest:
  
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - run: |
          dotnet restore
          cd Tests
          dotnet run -c release
          
