name: 'Upload last-master versions to MyGet'

on:
  push:
    branches:
      - main
    paths:
      - VERSION

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          
      - uses: actions/checkout@v2
        
      - name: 'Verify that the tests pass'
        run: |
          dotnet restore
          dotnet test -c release || dotnet test -c release || dotnet test -c release
        
      - name: 'Push new packages to nuget'
        run: |
          # versioning
          commithash=$(git rev-parse --short HEAD)
          currtime=$(date +%s)
          version=$(cat ./VERSION)
          echo "commit hash is $commithash"
          echo "time is $currtime"
          echo "version is $version"
          name=$version
          
          cd Sources

          # CodegenAnalysis
          cd CodegenAnalysis
          dotnet restore
          dotnet build -c release
          dotnet pack -c release -p:PackageVersion=$name
          cd bin/release
          dotnet nuget push CodegenAnalysis.$name.nupkg --api-key ${{ secrets.NUGET_KEY }} -s "nuget"
          cd ../../..
          
          # CodegenAnalysis.Assertions
          cd CodegenAnalysis.Assertions
          dotnet restore
          dotnet build -c release
          dotnet pack -c release -p:PackageVersion=$name
          cd bin/release
          dotnet nuget push CodegenAnalysis.Assertions.$name.nupkg --api-key ${{ secrets.NUGET_KEY }} -s "nuget"
          cd ../../..
          
          # CodegenAnalysis.Benchmarks
          cd CodegenAnalysis.Benchmarks
          dotnet restore
          dotnet build -c release
          dotnet pack -c release -p:PackageVersion=$name
          cd bin/release
          dotnet nuget push CodegenAnalysis.Benchmarks.$name.nupkg --api-key ${{ secrets.NUGET_KEY }} -s "nuget"
          cd ../../..
